### ISSUE TITLE
Add CLI `--help` text to README

### ISSUE THREAD

**Issue by georgeaf99** [xuset/planktos#14]
The documentation for specifying a web seed and recursive files should be in the README.

**Comment by xuset** [comment]
A CLI usage section would be helpful

Maybe even an additional section on how to seed a planktos website using a webtorrent compatible torrent client since this requires manually specifying the web seed url.

**Comment by georgeaf99** [comment]
I actually don't think that this is necessary, since they can access this information via the CLI.
