### ISSUE TITLE
Clean planktos directory when the CLI regenerates a torrent

### ISSUE THREAD

**Issue by georgeaf99** [xuset/planktos#19]

**Comment by xuset** [comment]
There are some good reasons for keeping the directory around:
 * Users on the old torrent can still download files from the webseed
 * If the contents of the file haven't changed, then the file is not copied again in setup.js

The directory will keep growing though and that'll be problematic.

**Comment by georgeaf99** [comment]
I think we should delete it until we have a solution for offering the user options as to how to deal with these files

**Comment by xuset** [comment]
What are the negatives of keeping it around other than it accumulates in size?

**Comment by georgeaf99** [comment]
Possible Use Case: Deployment script on server, which doesn't do a full clean of the website. It could result in servers going out of memory after a few months.

**Comment by xuset** [comment]
The negatives of removing the directories' files automatically in the cli seem to outweigh the positives to me.

I think it's reasonable if someone wants to delete the directory every time they run the cli they can do so with `rm -r planktos; planktos ...`. We could make it more clear in the docs that the directory is not cleaned automatically?

**Comment by xuset** [comment]
Closed for now, if this becomes an issue later on we can reopen it
