### ISSUE TITLE
Add custom tracker flag to CLI

### ISSUE THREAD

**Issue by xuset** [xuset/planktos#25]
The CLI should have a flag that allows the user to specify a custom tracker.

Passing the array/string that minimist generates into the `opts` for create-torrent will accomplish this.

As a side note, if a boolean false is passed into this option then create-torrent includes no trackers in the torrent meta. This is useful when testing so we are not bombarding trackers with our announces every time we run a test. The tests don't use trackers so there really isn't a point in announcing to them.

**Comment by alvin319** [comment]
I want to take a look at this one and possibly finish it! Any pointers for this one so I can take a look at the code?

**Comment by georgeaf99** [comment]
@alvin319 I'm not sure we should handle this issue right now... It would require that the CLI create a config file. We should discuss whether or not this feature is necessary for the MVP.

**Comment by alvin319** [comment]
👍
