### ISSUE TITLE
Add web stream support

### ISSUE THREAD

**Issue by xuset** [xuset/planktos#29]
Planktos should use [WhatWG ReadableStreams](https://streams.spec.whatwg.org/) in order to allow content to be streamed from IndexedDB and into the fetch event's respondWith. This will greatly speed up page load times and allow for video/audio streaming.

Reading from indexeddb-chunk-store with a nodejs stream while the file is not fully downloaded was added in #28 which is the bulk of the work.

What is needed for streaming is:
 * Convert nodejs streams to web streams
 * Use web streams when available for respondWith
 * Add support for byte range requests #6 (only needed for video and audio streaming)

**Comment by ChrisChiasson** [comment]
Fyi the Mozilla bug referenced on the readme.md (regarding streaming limitations) for this repo has been fixed with a series of patches (about 5 months ago)
