### ISSUE TITLE
Use file mime type to set Content-Type and blob.type

### ISSUE THREAD

**Issue by xuset** [xuset/planktos#30]
Setting these values correctly helps the browser and possible end user detect what type of file is being read.

The ~~~service worker~~~ fetch() method should set the Content-Type header for responses that are for files in the torrent.

Also when blobs are created we should also construct the blob with the correct mime type.

The very helpful [mime npm](https://www.npmjs.com/package/mime) can do the mime type detection

**Comment by xuset** [comment]
One possible implementation would be to add a `mime` property to File, and when File.getBlob() is called, set the blob's mime type to the value of `file.mime`. Then in fetch(), set the Reponse header based on `blob.type`.

**Comment by georgeaf99** [comment]
After perma-torrent is integrated into Planktos, all that is left to do is assign the `Content-Type` header using the mime type

**Comment by georgeaf99** [comment]
When we map requests for files from the actual file paths to the file hashes in the Planktos directory, we lose information regarding the file extension.... So the responsibility for detecting mime types needs to be in `Planktos`, not `aether-torrent`
