### ISSUE TITLE
Polish Up the Website

### ISSUE THREAD

**Issue by georgeaf99** [xuset/planktos#33]
The website needs some tweaks to make it look a bit more legit.

Tweaks:
- [x] Fix favicon
- [x] Planktos logo should be in the top left
- [x] Add a contact us section
- [x] Remove unnecessary empty space between sections
- [x] Add Google analytics (make sure Planktos bugs are tracked)
- [x] Add a **big** "Download Planktos" link pointing to the GitHub page after the about section
- [x] Make text larger
- [x] Fix unreferenced google error

Concerns:
- [ ] Not enough information is displayed on the initial page
- [x] Perhaps the about section could be formatted better (maybe tiles or something?)
- [x] The link to our GitHub should be available from anywhere in the website
- [ ] Background image is not really relevant and takes up a large amount of space

**Comment by georgeaf99** [comment]
As Per our Discussion Last Night:
- The about section should be tiled into two vertical columns with alternating colors, where elements are positioned from left to right and then top to bottom. 
- Add the GitHub logo to the top right of our page
- Remove padding in the content sections

**Comment by xuset** [comment]
Contact info added in 7161b2c
