### ISSUE TITLE
Documentation for Planktos API

### ISSUE THREAD

**Issue by georgeaf99** [xuset/planktos#49]
The public API is quite simple; however, it is not clear what our contracts to the user are. 

For example:
- `getSnapshot` not only gets the latest snapshot, but it also seeds the file if it wasn't being seeded before
- `getSnapshot` can only be called after `update`
- `fetch` and `getFile` have the same side effects and constraints as `getSnapshot`

Some of this may be a problem with our API; however, documentation is necessary regardless of whether or not these are issues.

**Comment by xuset** [comment]
Api documentation is now on the wiki and the api problems were fixed in #51 😄
