### ISSUE TITLE
Make the CLI more usable

### ISSUE THREAD

**Issue by georgeaf99** [xuset/planktos#8]
The CLI currently does not conform to the expected user interface. Specific concerns:
- Installing the library should be one command
- Bundling files into a torrent should be a separate command

**Comment by xuset** [comment]
One of the primary goals of the CLI should be as usable as possible. It's not immediately obvious to me how splitting up the functionality into separate commands makes it more usable, can you explain?

**Comment by georgeaf99** [comment]
I think the typical interface pattern of CLIs is to have subcommands for each type of action that can be made. Thus, the flags are unique to each type of subcommand, not global. Subcommands for the Planktos CLI:

`planktos install-lib` => copies the library files
`planktos bundle` => bundles the website files to torrent

**Comment by georgeaf99** [comment]
After looking at the CLI I now see that you can perform both of those actions in one command; however, in the setup section of the readme the instructions are to install the library only and then bundle the files into a torrent. This seems to make more sense to me, since you may want to update the library or torrent files without updating the other.

**Comment by xuset** [comment]
The reason there is a lib-only option is because the first time planktos is installed, the html needs to include the lib's script file before the torrent is created so the updated html is included in the torrent. All subsequent uses of the tool should both copy the lib and create the torrent. The first use is the only time I that I think of that someone would just want to copy the lib files. It makes more sense to me to perform both functions by default since that is what is wanted most of the time and leave the first time as the edge case. Thoughts?

**Comment by georgeaf99** [comment]
Why doesn't the CLI simply copy the library before packaging the torrent? Unless I'm missing something, it seems like that would fix the issue?

However, it seems like someone may actually want to update the library without updating the torrent or vice versa. Possible use case: a deployment script packages the website into a torrent, but doesn't update the library, since code versions should be frozen unless explicitly updated.

Updating one without the other implies the backwards compatibility of the library with old torrent formats

**Comment by georgeaf99** [comment]
If you think that this is a reasonable use case, we can still support the more convenient version using  subcommands like this:
- _planktos install-lib_
- _planktos bundle_
- _planktos package_ => lib and torrent

**Comment by xuset** [comment]
It just seems unnecessary to me and complicates things slightly. If you think it's a good fix then go for it

**Comment by xuset** [comment]
It's just that the first time planktos is installed requires manually modifying some of the website's files to include the planktos lib script. But the lib script doesn't exist until it's copied over with --lib-only, and it's important to manually include the script in the html before the torrent is created so the modified html is in the torrent.

It is possible to update the library without updating the torrent with --lib-only. The library that is copied over is identical to the previous one that was copied over and will only differ if planktos is explicitly updated through npm.

I do agree that initial install is complicated and we should find a way to simplify things, but I don't think making sub-commands will achieve.

**Comment by xuset** [comment]
The simplest and must usable CLI are ones that do one thing and do it well. We should strive for that when making our CLI. I think the current CLI does one thing well, but the initial install requires doing half of that one thing (--lib-only). The main reason I'm against splitting the cli into multiple sub commands is that we are exposing a more complicated interface than the 'do one thing and do it well'

**Comment by xuset** [comment]
I do want to make the CLI more usable, and I think the best place to start that is eliminating the edge case for the initial install. If that's eliminated then the CLI will only do one thing and do it well. There will no longer be a need for doing just half, for a one time exception.

**Comment by georgeaf99** [comment]
Getting rid of the exception seems like the best solution to me. Can you elaborate on how that would be accomplished?

**Comment by xuset** [comment]
One simple way would be to improve the docs. See #21

**Comment by xuset** [comment]
@georgeaf99 with the updated readme merged in, is this still an issue?

**Comment by georgeaf99** [comment]
I guess not now. We should look for feedback on this though.
