### ISSUE TITLE
Add cool tags and stuff

### ISSUE THREAD

**Issue by georgeaf99** [xuset/planktos#9]
We should have a Travis CI build tag, NPM tag, and maybe a donate button...

This should make us look like professionals!

**Comment by xuset** [comment]
Feel free to add them!

**Comment by xuset** [comment]
We can also add the saucelabs browser matrix which shows the browsers that are passing the tests. See https://wiki.saucelabs.com/display/DOCS/Using+Status+Badges+and+the+Browser+Matrix+Widget+to+Monitor+Test+Results

**Comment by georgeaf99** [comment]
Done 👍
